# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([135, 148, 132,  62,   5, 183,  67,  45,  48, 134,  31,  21],
      dtype=int32)

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[ 29,  73,  28, 160],
       [169,  77,  47, 127],
       [ 34,  90, 121, 193]], dtype=int32)

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[159,  66,  20,  41,  34, 169],
        [ 51,  23,  73,  31, 119,  58],
        [146, 159, 147,  35, 168,  70]],

       [[  6, 171,  22, 166,  88, 145],
        [127, 148, 157,  67, 147,  49],
        [  5, 106,  51,  80,  49,  31]]], dtype=int32)

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1, 148, 132,  62,   5, 183,  67,  45,  48, 134,  31,  21],
      dtype=int32)

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[ 29,  73,  28, 160],
       [169,  77,  -1, 127],
       [ 34,  90, 121, 193]], dtype=int32)

In [8]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[159,  66,  20,  41,  34, 169],
        [ 51,  23,  73,  31, 119,  58],
        [146, 159, 147,  35, 168,  70]],

       [[  6, 171,  22, 166,  88, 145],
        [127, 148, 157,  67, 147,  49],
        [  5, 106,  51,  80,  -1,  31]]], dtype=int32)

In [9]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1, 148, 132,  62,   5, 183,  67,  45,  48, 134,  31,  21, 100,
       130])

In [10]:
a1D # a1D não foi modificado

array([ -1, 148, 132,  62,   5, 183,  67,  45,  48, 134,  31,  21],
      dtype=int32)

In [11]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([ 29,  73,  28, 160, 169,  77,  -1, 127,  34,  90, 121, 193, 100,
       130])

In [12]:
a2D # a2D não foi modificado

array([[ 29,  73,  28, 160],
       [169,  77,  -1, 127],
       [ 34,  90, 121, 193]], dtype=int32)

In [13]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([159,  66,  20,  41,  34, 169,  51,  23,  73,  31, 119,  58, 146,
       159, 147,  35, 168,  70,   6, 171,  22, 166,  88, 145, 127, 148,
       157,  67, 147,  49,   5, 106,  51,  80,  -1,  31, 100, 130])

In [14]:
a3D # a3D não foi modificado

array([[[159,  66,  20,  41,  34, 169],
        [ 51,  23,  73,  31, 119,  58],
        [146, 159, 147,  35, 168,  70]],

       [[  6, 171,  22, 166,  88, 145],
        [127, 148, 157,  67, 147,  49],
        [  5, 106,  51,  80,  -1,  31]]], dtype=int32)

In [15]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1 148 132  62   5 183  67  45  48 134  31  21 100 130]
[132   5 183  67  45  48 134  31  21 100 130]


### Comparação entre arrays

In [16]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [17]:
c1D = np.random.randint(1,10,20)
c1D

array([3, 7, 7, 3, 2, 3, 5, 1, 7, 3, 7, 2, 2, 3, 9, 4, 9, 5, 3, 8],
      dtype=int32)

In [18]:
c1D == 5

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False])

In [20]:
c1D[c1D == 5]

array([5, 5], dtype=int32)

### Operações entre arrays e escalares

In [21]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [25]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [26]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [27]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [29]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [30]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [31]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [32]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [33]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [34]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [35]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [36]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [37]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [38]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [39]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [41]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[88, 92, 57, 22, 74, 30, 38, 61, 31, 40],
       [75, 79, 27, 75, 60, 75, 89, 72, 57, 51],
       [25, 10, 38,  4, 92, 28, 43, 71, 27,  1],
       [52, 79, 32, 32,  8, 66, 48, 89, 78, 53],
       [97, 41, 63,  6,  3, 61, 59, 41, 93, 15]], dtype=int32)

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [42]:
# Soma de todos os elementos
d2D.sum()

np.int64(2548)

In [43]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([337, 301, 217, 139, 237, 260, 277, 334, 286, 160])

In [44]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([533, 660, 339, 537, 479])

In [45]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([337, 301, 217, 139, 237, 260, 277, 334, 286, 160], dtype=int32)

In [46]:
# Retorna o menor valor geral
d2D.min()

np.int32(1)

In [47]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([25, 10, 27,  4,  3, 28, 38, 41, 27,  1], dtype=int32)

In [50]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([22, 27,  1,  8,  3], dtype=int32)

In [51]:
# Retorna o maior valor geral
d2D.max()

np.int32(97)

In [52]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([97, 92, 63, 75, 92, 75, 89, 89, 93, 53], dtype=int32)

In [53]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([92, 89, 92, 89, 97], dtype=int32)

In [54]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  88,  180,  237,  259,  333,  363,  401,  462,  493,  533,  608,
        687,  714,  789,  849,  924, 1013, 1085, 1142, 1193, 1218, 1228,
       1266, 1270, 1362, 1390, 1433, 1504, 1531, 1532, 1584, 1663, 1695,
       1727, 1735, 1801, 1849, 1938, 2016, 2069, 2166, 2207, 2270, 2276,
       2279, 2340, 2399, 2440, 2533, 2548])

In [55]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 88,  92,  57,  22,  74,  30,  38,  61,  31,  40],
       [163, 171,  84,  97, 134, 105, 127, 133,  88,  91],
       [188, 181, 122, 101, 226, 133, 170, 204, 115,  92],
       [240, 260, 154, 133, 234, 199, 218, 293, 193, 145],
       [337, 301, 217, 139, 237, 260, 277, 334, 286, 160]])

In [56]:
d2D

array([[88, 92, 57, 22, 74, 30, 38, 61, 31, 40],
       [75, 79, 27, 75, 60, 75, 89, 72, 57, 51],
       [25, 10, 38,  4, 92, 28, 43, 71, 27,  1],
       [52, 79, 32, 32,  8, 66, 48, 89, 78, 53],
       [97, 41, 63,  6,  3, 61, 59, 41, 93, 15]], dtype=int32)

In [57]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 88, 180, 237, 259, 333, 363, 401, 462, 493, 533],
       [ 75, 154, 181, 256, 316, 391, 480, 552, 609, 660],
       [ 25,  35,  73,  77, 169, 197, 240, 311, 338, 339],
       [ 52, 131, 163, 195, 203, 269, 317, 406, 484, 537],
       [ 97, 138, 201, 207, 210, 271, 330, 371, 464, 479]])

In [58]:
# Retorna a média aritmética
d2D.mean()

np.float64(50.96)

In [59]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([67.4, 60.2, 43.4, 27.8, 47.4, 52. , 55.4, 66.8, 57.2, 32. ])

In [60]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([53.3, 66. , 33.9, 53.7, 47.9])

In [61]:
# Retorna o desvio padrão
d2D.std()

np.float64(27.218346753614554)

In [62]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([26.05071976, 30.35391243, 14.12232276, 25.77130187, 35.71890256,
       19.31838503, 18.18350901, 15.7276826 , 25.74024087, 20.57182539])

In [63]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([23.73625918, 16.85229955, 27.49709076, 23.86231338, 31.49110986])

In [64]:
# Retorna a mediana (geral)
np.median(d2D)

np.float64(52.5)

In [65]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([75., 79., 38., 22., 60., 61., 48., 71., 57., 40.])

In [66]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([48.5, 73.5, 27.5, 52.5, 50. ])

### Copiando e concatenando arrays

In [69]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[47, 47, 21, 29,  9],
       [22,  2, 32, 32, 44],
       [36,  6, 25,  6,  6],
       [ 5, 19, 26, 22, 25]], dtype=int32)

In [70]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[71, 90, 56, 51, 59],
       [63, 64, 94, 87, 99],
       [56, 64, 97, 62, 66],
       [51, 60, 77, 88, 69]], dtype=int32)

In [71]:
c2D = a2D
c2D

array([[47, 47, 21, 29,  9],
       [22,  2, 32, 32, 44],
       [36,  6, 25,  6,  6],
       [ 5, 19, 26, 22, 25]], dtype=int32)

In [72]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[47, 47, 21, 29, -1],
       [22, -1, 32, 32, 44],
       [36, -1, 25, -1, -1],
       [-1, -1, 26, 22, 25]], dtype=int32)

In [73]:
a2D 

array([[47, 47, 21, 29, -1],
       [22, -1, 32, 32, 44],
       [36, -1, 25, -1, -1],
       [-1, -1, 26, 22, 25]], dtype=int32)

Os elementos de a2D também foram alterados. :-(

In [74]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[38,  7,  7, 35,  7],
       [18, 40,  1,  7, 18],
       [40,  5, 11, 21, 39],
       [28,  1, 17, 14, 45]], dtype=int32)

In [75]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[38,  7,  7, 35,  7],
       [18, 40,  1,  7, 18],
       [40,  5, 11, 21, 39],
       [28,  1, 17, 14, 45]], dtype=int32)

In [76]:
c2D[c2D < 20] = -1
c2D

array([[38, -1, -1, 35, -1],
       [-1, 40, -1, -1, -1],
       [40, -1, -1, 21, 39],
       [28, -1, -1, -1, 45]], dtype=int32)

In [77]:
a2D

array([[38,  7,  7, 35,  7],
       [18, 40,  1,  7, 18],
       [40,  5, 11, 21, 39],
       [28,  1, 17, 14, 45]], dtype=int32)

Agora sim!!!

### Ordenando os elementos de um array

In [78]:
a1D = np.random.randint(1,100, 15)
a1D

array([20, 27, 59, 67, 91, 55, 93, 12,  2,  4, 52, 53, 86, 36, 83],
      dtype=int32)

In [79]:
a1D.sort()
a1D

array([ 2,  4, 12, 20, 27, 36, 52, 53, 55, 59, 67, 83, 86, 91, 93],
      dtype=int32)

In [80]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[91, 43,  7, 14, 53,  5, 58, 65, 66, 59],
       [68, 13, 63, 77, 84, 25, 45, 37, 73, 11],
       [44, 25, 47, 91, 81, 86, 48, 18, 40, 30],
       [20, 49, 60, 25, 92, 23, 82, 47, 18, 65],
       [72, 85, 67, 44, 79, 86, 15, 44, 19, 37],
       [49, 33, 26, 86, 95, 51, 13, 50, 26, 20]], dtype=int32)

In [81]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[ 5,  7, 14, 43, 53, 58, 59, 65, 66, 91],
       [11, 13, 25, 37, 45, 63, 68, 73, 77, 84],
       [18, 25, 30, 40, 44, 47, 48, 81, 86, 91],
       [18, 20, 23, 25, 47, 49, 60, 65, 82, 92],
       [15, 19, 37, 44, 44, 67, 72, 79, 85, 86],
       [13, 20, 26, 26, 33, 49, 50, 51, 86, 95]], dtype=int32)

In [82]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 5,  7, 14, 25, 33, 47, 48, 51, 66, 84],
       [11, 13, 23, 26, 44, 49, 50, 65, 77, 86],
       [13, 19, 25, 37, 44, 49, 59, 65, 82, 91],
       [15, 20, 26, 40, 45, 58, 60, 73, 85, 91],
       [18, 20, 30, 43, 47, 63, 68, 79, 86, 92],
       [18, 25, 37, 44, 53, 67, 72, 81, 86, 95]], dtype=int32)

In [83]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[69, 58, 72, 51,  7, 69, 13, 43, 50, 79],
       [84, 76,  2, 26, 80, 10, 47, 25, 13, 73],
       [25,  7, 96, 53, 74, 78,  2, 18, 64, 39],
       [82, 13, 18, 42, 21, 21, 38, 65, 69, 31],
       [12, 79, 18, 42, 84, 40, 96,  4, 87, 92],
       [72, 15, 82, 99, 83, 68, 64, 92, 26, 62]], dtype=int32)

In [84]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 7, 13, 43, 50, 51, 58, 69, 69, 72, 79],
       [ 2, 10, 13, 25, 26, 47, 73, 76, 80, 84],
       [ 2,  7, 18, 25, 39, 53, 64, 74, 78, 96],
       [13, 18, 21, 21, 31, 38, 42, 65, 69, 82],
       [ 4, 12, 18, 40, 42, 79, 84, 87, 92, 96],
       [15, 26, 62, 64, 68, 72, 82, 83, 92, 99]], dtype=int32)

### Transposição de arrays

In [93]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [95]:
a2DT = a2D.transpose() # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [96]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
a2D # a2D original não foi transposto

### Mudando o formato de um array - reshape()

In [98]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [99]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [100]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [101]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [102]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [103]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [104]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [105]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[21, 21, 89, 46, 74, 77, 41, 35, 40],
       [38, 21, 79,  1, 30, 13, 34, 18, 22],
       [52, 23, 66, 35, 26, 31, 78, 69, 84]], dtype=int32)

In [106]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[83, 42, 21, 84, 14, 14,  5, 44, 69],
       [84, 53, 88, 91,  3, 64, 31, 13, 22],
       [13, 46, 14, 36, 58, 63, 27, 53, 41],
       [84, 28,  1,  5, 17, 18, 99,  8, 49],
       [84, 78, 18, 83, 75, 69, 29, 90, 49]], dtype=int32)

In [107]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[ 81,  68,  61,  75],
       [  7,  28,  39,   3],
       [  6,  99,  54,  44],
       [100,  81,  80,  48],
       [ 73,  51,  67,  28]], dtype=int32)

In [108]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [109]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [110]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]]

b2D
[[83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

Concatenação
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]
 [83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]


In [111]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]]

b2D
[[83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

Concatenação
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]
 [83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]


In [112]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

c2D
[[ 81  68  61  75]
 [  7  28  39   3]
 [  6  99  54  44]
 [100  81  80  48]
 [ 73  51  67  28]]

Concatenação
[[ 83  42  21  84  14  14   5  44  69  81  68  61  75]
 [ 84  53  88  91   3  64  31  13  22   7  28  39   3]
 [ 13  46  14  36  58  63  27  53  41   6  99  54  44]
 [ 84  28   1   5  17  18  99   8  49 100  81  80  48]
 [ 84  78  18  83  75  69  29  90  49  73  51  67  28]]


In [113]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

c2D
[[ 81  68  61  75]
 [  7  28  39   3]
 [  6  99  54  44]
 [100  81  80  48]
 [ 73  51  67  28]]

Concatenação
[[ 83  42  21  84  14  14   5  44  69  81  68  61  75]
 [ 84  53  88  91   3  64  31  13  22   7  28  39   3]
 [ 13  46  14  36  58  63  27  53  41   6  99  54  44]
 [ 84  28   1   5  17  18  99   8  49 100  81  80  48]
 [ 84  78  18  83  75  69  29  90  49  73  51  67  28]]


### Dividindo arrays

In [114]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]
 [83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

1a parte
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]
 [83 42 21 84 14 14  5 44 69]]

2a parte
[[84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]


In [115]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[21 21 89 46 74 77 41 35 40]
 [38 21 79  1 30 13 34 18 22]
 [52 23 66 35 26 31 78 69 84]
 [83 42 21 84 14 14  5 44 69]
 [84 53 88 91  3 64 31 13 22]
 [13 46 14 36 58 63 27 53 41]
 [84 28  1  5 17 18 99  8 49]
 [84 78 18 83 75 69 29 90 49]]

1a parte
[[21 21 89]
 [38 21 79]
 [52 23 66]
 [83 42 21]
 [84 53 88]
 [13 46 14]
 [84 28  1]
 [84 78 18]]

2a parte
[[46 74 77]
 [ 1 30 13]
 [35 26 31]
 [84 14 14]
 [91  3 64]
 [36 58 63]
 [ 5 17 18]
 [83 75 69]]

3a parte
[[41 35 40]
 [34 18 22]
 [78 69 84]
 [ 5 44 69]
 [31 13 22]
 [27 53 41]
 [99  8 49]
 [29 90 49]]
