# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([1, 0, 5, 0, 9, 1, 3, 7, 6, 9], dtype=int32)

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[46, 16,  8, 81, 58],
       [26,  1, 90, 45, 49],
       [ 9, 84, 10, 95, 95],
       [18, 67, 49, 57, 54]], dtype=int32)

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.55807086, 0.98927905, 0.80147467, 0.36448492, 0.54429756],
        [0.63127105, 0.79846609, 0.23786296, 0.94720552, 0.23931266],
        [0.22078544, 0.3091708 , 0.38737871, 0.79887658, 0.39077435],
        [0.44273578, 0.49980144, 0.3255067 , 0.64976213, 0.6961361 ]],

       [[0.28143127, 0.76713274, 0.52215831, 0.56336594, 0.47276354],
        [0.37263005, 0.14519527, 0.58973176, 0.39762374, 0.08874483],
        [0.09364725, 0.8451342 , 0.54805487, 0.3643921 , 0.15734886],
        [0.91586848, 0.17434383, 0.57745555, 0.37899614, 0.61149493]],

       [[0.99208834, 0.34942542, 0.0480749 , 0.89103488, 0.16699786],
        [0.17887129, 0.85542756, 0.34654686, 0.862252  , 0.34267514],
        [0.83011862, 0.99620042, 0.88418668, 0.7691915 , 0.7301471 ],
        [0.0718358 , 0.59041745, 0.86147749, 0.0207961 , 0.17417394]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'