In [78]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 0] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [84]:
a = np.zeros(10) + 4
a

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [91]:
arr = np.eye(5)
arr = arr - (np.eye(5) + 1)
arr

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [92]:
import numpy as np
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


In [105]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[-2::-2] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])